// <auto-generated />
namespace shippingCodefirstTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class display_name_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(display_name_test));
        
        string IMigrationMetadata.Id
        {
            get { return "201509141508324_display_name_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
