// <auto-generated />
namespace shippingCodefirstTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderHistory_nameChange_From_Id_to_OrderId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderHistory_nameChange_From_Id_to_OrderId));
        
        string IMigrationMetadata.Id
        {
            get { return "201509022132047_OrderHistory_nameChange_From_Id_to_OrderId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
